-- Add student details columns to users table
ALTER TABLE users 
ADD COLUMN middle_name VARCHAR(100) NULL AFTER name,
ADD COLUMN date_of_birth DATE NULL,
ADD COLUMN gender ENUM('Male', 'Female') NULL,
ADD COLUMN age INT NULL,
ADD COLUMN place_of_birth VARCHAR(255) NULL,
ADD COLUMN nationality VARCHAR(100) NULL,
ADD COLUMN religion VARCHAR(100) NULL,
ADD COLUMN home_address TEXT NULL,
ADD COLUMN contact_number VARCHAR(20) NULL,
ADD COLUMN father_name VARCHAR(255) NULL,
ADD COLUMN father_occupation VARCHAR(100) NULL,
ADD COLUMN father_contact VARCHAR(20) NULL,
ADD COLUMN mother_name VARCHAR(255) NULL,
ADD COLUMN mother_occupation VARCHAR(100) NULL,
ADD COLUMN mother_contact VARCHAR(20) NULL,
ADD COLUMN guardian_name VARCHAR(255) NULL,
ADD COLUMN guardian_contact VARCHAR(20) NULL,
ADD COLUMN guardian_relationship VARCHAR(50) NULL,
ADD COLUMN last_school_attended VARCHAR(255) NULL,
ADD COLUMN last_school_address TEXT NULL,
ADD COLUMN school_year_completed VARCHAR(20) NULL,
ADD COLUMN general_average VARCHAR(10) NULL,
ADD COLUMN has_lrn BOOLEAN DEFAULT FALSE,
ADD COLUMN lrn_number VARCHAR(20) NULL,
ADD COLUMN is_returnee BOOLEAN DEFAULT FALSE,
ADD COLUMN is_transfer_in BOOLEAN DEFAULT FALSE,
ADD COLUMN has_special_needs BOOLEAN DEFAULT FALSE,
ADD COLUMN special_needs_type VARCHAR(255) NULL,
ADD COLUMN is_4ps_beneficiary BOOLEAN DEFAULT FALSE,
ADD COLUMN is_indigenous BOOLEAN DEFAULT FALSE,
ADD COLUMN indigenous_group VARCHAR(100) NULL,
ADD COLUMN mother_tongue VARCHAR(100) NULL;
